# Generated by Django 6.0.3 on 2026-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='content',
            field=models.TextField(blank=True, verbose_name='学習内容'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='タイトル'),
        ),
    ]
