# Generated by Django 6.0.3 on 2026-04-05 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_studyrecord_content_alter_studyrecord_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'ordering': ['-date'], 'verbose_name': '学習記録', 'verbose_name_plural': '学習記録'},
        ),
        migrations.RenameField(
            model_name='studyrecord',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='studyrecord',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studyrecord',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='date',
            field=models.DateField(verbose_name='学習日'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='学習時間'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学習項目名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '学習項目',
                'verbose_name_plural': '学習項目',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='records.certification', verbose_name='学習項目'),
        ),
    ]
